### ISSUE TITLE
Streams not starting: "No MOOV in stream"

### ISSUE THREAD

**Issue by pl0ng** [add-ons/plugin.video.streamz#29] opened 2020-12-31 13:47 UTC
Hi,

Using R-Pi 3b with latest OSMC software.
Streamz 1.0.2

Nothing in the library plays, giving following error in de kodi.log:
2020-12-31 14:38:20.264 T:1916080144  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.streamz/play/catalog/episodes/*snip*
2020-12-31 14:38:20.266 T:983523552  NOTICE: Creating InputStream
2020-12-31 14:38:20.639 T:983523552   ERROR: AddOnLog: InputStream Adaptive: Download https://dcs-vod.apis.anvato.net/vod/p/https://dpp-anvato-live.akamaized.net/eu/vod/*snip*
2020-12-31 14:38:20.640 T:983523552   ERROR: AddOnLog: InputStream Adaptive: No MOOV in stream!
2020-12-31 14:38:20.675 T:1210052832   ERROR: AddOnLog: InputStream Adaptive: Download https://dcs-vod.apis.anvato.net/vod/p/https://dpp-anvato-live.akamaized.net/eu/vod/*snip*
2020-12-31 14:38:20.677 T:983523552   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.streamz/play/catalog/episodes/*snip*
2020-12-31 14:38:20.677 T:983523552  NOTICE: CVideoPlayer::OnExit()
2020-12-31 14:38:20.708 T:1916080144  NOTICE: CVideoPlayer::CloseFile()
2020-12-31 14:38:20.708 T:1916080144  NOTICE: VideoPlayer: waiting for threads to exit
2020-12-31 14:38:20.708 T:1916080144  NOTICE: VideoPlayer: finished waiting
2020-12-31 14:38:21.236 T:1090515168 WARNING: [plugin.video.streamz] [resources.lib.kodiplayer] Player: PlayBackStopped triggered while waiting for start.

Ps: my inputstream adapative should be ok since VTMgo is running OK.

**Comment by michaelarnauts** [comment] 2020-12-31 14:00
VTM Go is recently updated and it doesn't need the updated Inputstream anymore. You'll need to download the latest master branch of this add-on since that also contains the same workaround.

**Comment by michaelarnauts** [comment] 2020-12-31 14:02
See https://github.com/add-ons/plugin.video.streamz/wiki/Installatie for how to install the development code.

Closing as duplicate of #22

**Closed by michaelarnauts** 2020-12-31 14:02 UTC
